build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-debian:trixie"
  amd64: "ghcr.io/home-assistant/amd64-base-debian:trixie"
labels:
  org.opencontainers.image.title: "TOMMY (Home Assistant Add-on)"
  org.opencontainers.image.description: "Home Assistant Add-on for TOMMY"
  org.opencontainers.image.source: "https://github.com/tommy-sense/homeassistant-addon"
  org.opencontainers.image.licenses: "SEE LICENSE IN LICENSE.md"
args:
  TEMPIO_VERSION: "2021.09.0"